#!/usr/bin/env bash

KZENV_REMOTE_API="https://api.github.com/repos/kubernetes-sigs/kustomize/releases"
KZENV_REMOTE_DOWNLOAD="https://github.com/kubernetes-sigs/kustomize/releases/download"

function error_and_die() {
  echo -e "kzenv: $(basename ${0}): \033[0;31m[ERROR] ${1}\033[0;39m" >&2
  exit 1
}

function warn_and_continue() {
  echo -e "kzenv: $(basename ${0}): \033[0;33m[WARN] ${1}\033[0;39m" >&2
}

function info() {
  echo -e "\033[0;32m[INFO] ${1}\033[0;39m"
}

# Curl wrapper to switch TLS option for each OS
function curlw () {
  local TLS_OPT="--tlsv1.2"

  # Check if curl is 10.12.6 or above
  if [[ -n "$(command -v sw_vers 2>/dev/null)" && ("$(sw_vers)" =~ 10\.12\.([6-9]|[0-9]{2}) || "$(sw_vers)" =~ 10\.1[3-9]) ]]; then
    TLS_OPT=""
  fi

  # info ${TLS_OPT} "$@"
  curl ${TLS_OPT} "$@"
}