#!/usr/bin/env bash

[ -n "${KZENV_DEBUG}" ] && set -x
source "${KZENV_ROOT}/libexec/helpers"

[ "${#}" -gt 1 ] && error_and_die "usage: kzenv uninstall [<version>]"

declare version_requested version regex

if [ -z "${1}" ]; then
  version_file="$(kzenv-version-file)"
  if [ "${version_file}" != "${KZENV_ROOT}/version" ];then
    version_requested="$(cat "${version_file}" || true)"
  fi
else
  version_requested="${1}"
fi

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex=""
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

[ -n "${version}" ] || error_and_die "Version is not specified"
version="$(kzenv-list | sed -E 's/^(\*| )? //g; s/ \(set by .+\)$//' | grep -e "${regex}" | head -n 1)"
[ -n "${version}" ] || error_and_die "No versions matching '${1}' found in local"

dst_path="${KZENV_ROOT}/versions/${version}"
if [ -f "${dst_path}/kustomize" ]; then
  info "Uninstall Kustomize v${version}"
  rm -r "${dst_path}"
  info "\033[0;32mKustomize v${version} is successfully uninstalled\033[0;39m"
fi