#!/usr/bin/env bash

set -e

[ -n "${KZENV_DEBUG}" ] && set -x
source "${KZENV_ROOT}/libexec/helpers"

if [ "${#}" -ne 0 ];then
  echo "usage: kzenv list-remote" 1>&2
  exit 1
fi


function add_headers {

  echo ${header}
}

function github_extract {
  local url=$1
  headers=add_headers
  if [ -n "${GITHUB_API_TOKEN}" ]; then
    request="${url} --header \"Authorization: token ${GITHUB_API_TOKEN}\""
  else
    request="${url}"
  fi
  # echo ${request}
  curlw -sf ${request} | \
    grep browser_download| \
    grep linux| \
    cut -d '"' -f 4| \
    grep "/kustomize"| \
    grep -v -E 'pluginator|api|pseudo' | \
    grep -o -E "[0-9]+\.[0-9]+\.[0-9]+" |
    uniq
}

last_page=`curl -s -I "${KZENV_REMOTE_API}" | grep '^link:' | sed -e 's/^link:.*page=//g' -e 's/>.*$//g'`

# does this result use pagination?
if [ -z "$last_page" ]; then
    # no - this result has only one page
    # echo "Only one page: ${KZENV_REMOTE_API}"
    github_extract "${KZENV_REMOTE_API}"
else
    # yes - this result is on multiple pages
    for p in `seq 1 $last_page`; do
      # echo "Page: ${p}"
      github_extract "${KZENV_REMOTE_API}?page=$p"
    done
fi
