#!/usr/bin/env bash

[ -n "${KZENV_DEBUG}" ] && set -x

echo "Usage: kzenv <command> [<options>]

Commands:
   install       Install a specific version of Kustomize
   use           Switch a version to use
   uninstall     Uninstall a specific version of Kustomize
   list          List all installed versions
   list-remote   List all installable versions
"