#!/usr/bin/env bash

[ -n "${KZENV_DEBUG}" ] && set -x
source "${KZENV_ROOT}/libexec/helpers"

[ "${#}" -ne 1 ] && error_and_die "usage: kzenv use <version>"

declare version_requested version regex

version_requested="${1}"

if [[ "${version_requested}" =~ ^min-required$ ]]; then
  echo "Detecting minimal required version..."
  found_min_required="$(kzenv-min-required)"

  if [[ $? -eq 0 ]]; then
      echo "Min required version is detected as ${found_min_required}"
      version_requested="${found_min_required}"
  else
    exit 1
  fi
fi

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex="^[0-9]\+\.[0-9]\+\.[0-9]\+$"
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

[ -d "${KZENV_ROOT}/versions" ] \
  || error_and_die "No versions of kustomize installed. Please install one with: kzenv install"

version="$(\ls "${KZENV_ROOT}/versions" \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)"

[ -n "${version}" ] || error_and_die "No installed versions of kustomize matched '${1}'"

target_path="${KZENV_ROOT}/versions/${version}"
[ -f "${target_path}/kustomize" ] \
  || error_and_die "Version directory for ${version} is present, but the kustomize binary is not! Manual intervention required."
[ -x "${target_path}/kustomize" ] \
  || error_and_die "Version directory for ${version} is present, but the kustomize binary is not executable! Manual intervention required. "

info "Switching to v${version}"
echo "${version}" > "$(kzenv-version-file)" || error_and_die "'switch to v${version} failed'"
kustomize version 1>/dev/null || error_and_die "'kustomize version' failed. Something is seriously wrong"
info "Switching completed"