#!/usr/bin/env bash
# Usage: kzenv version-file
# Summary: Detect the file that sets the current kzenv version
set -e
[ -n "${KZENV_DEBUG}" ] && set -x

find_local_version_file() {
  local root="${1}"
  while ! [[ "${root}" =~ ^//[^/]*$ ]]; do
    if [ -e "${root}/.kustomize-version" ]; then
      echo "${root}/.kustomize-version"
      return 0
    fi
    [ -n "${root}" ] || break
    root="${root%/*}"
  done
  return 1
}

find_local_version_file "${KZENV_DIR}" || find_local_version_file "${HOME}" || echo "${KZENV_ROOT}/version"