#!/usr/bin/env bash

set -e

[ -n "${KZENV_DEBUG}" ] && set -x
source "${KZENV_ROOT}/libexec/helpers"

if [ "${#}" -ne 0 ];then
  echo "usage: kzenv list-remote" 1>&2
  exit 1
fi

function github_extract() {
  local url=$1
  # info ${url}

  cmd="curlw -sf"
  if [ -n "${GITHUB_API_TOKEN}" ]; then
    cmd="${cmd} -H 'Authorization: token ${GITHUB_API_TOKEN}'"
  fi
  cmd="${cmd} ${url}"
  versions=$(eval "$cmd"|grep browser_download|grep linux|cut -d '"' -f 4|grep "/kustomize"|grep -v -E "pluginator|api|pseudo"|grep -o -E "[0-9]+\.[0-9]+\.[0-9]+" |uniq)
  echo -e ${versions} | tr ' ' '\n'
}


if [ -n "${GITHUB_API_TOKEN}" ]; then
  info "Use Github API token"
  last_page=$(curl -s -H "Authorization: token ${GITHUB_API_TOKEN}" -I ${KZENV_REMOTE_API} | grep '^Link:' | sed -e 's/^Link:.*page=//g' -e 's/>.*$//g')
else
  last_page=$(curl -s -I ${KZENV_REMOTE_API} | grep '^link:' | sed -e 's/^link:.*page=//g' -e 's/>.*$//g')
fi
# info ${last_page}

# does this result use pagination?
if [ -z "$last_page" ]; then
    # info "Only one page: ${KZENV_REMOTE_API}"
    github_extract "${KZENV_REMOTE_API}"
else
    for p in `seq 1 $last_page`; do
      # info "Page: ${p}"
      github_extract "${KZENV_REMOTE_API}?page=$p"
    done
fi
